apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

namespace: broker-with-interconnect-mesh

bases:
- ../../../../base/interconnect/mesh

resources:
  - cm.yaml

secretGenerator:
  #https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/pull/20
- name: users-secret-mesh
  envs:
  - users/users.properties
- name: policies-mesh
  files:
    - policies/default.json
    - policies/edge.json
    - policies/inter-router.json
    - policies/public.json
# copy from ZoneB crt/client-certs to be able to access amqps
# - name: remote-zoneb-router-cert
#   files:
#     - tls.crt=crt/remote-zone-b-certs/tls.crt
#     - tls.key=crt/remote-zone-b-certs/tls.key
#     - ca.crt=crt/remote-zone-b-certs/tls.crt
#   type: "kubernetes.io/tls"
#
# patches:
# - target:
#     kind: DeploymentConfig
#     name: amq-interconnect-mesh
#   patch: |-
#     - op: add
#       path: /spec/template/spec/containers/0/volumeMounts/-
#       value:
#         name: "remote-zoneb-router-cert"
#         mountPath: "/etc/qpid-dispatch-certs/remote-zoneb-router-cert/"
#     - op: add
#       path: /spec/template/spec/volumes/-
#       value:
#         name: "remote-zoneb-router-cert"
#         secret:
#           secretName: remote-zoneb-router-cert
