apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: amq-broker-
  annotations:
    olm.providedAPIs: >-
      ActiveMQArtemis.v2alpha4.broker.amq.io,ActiveMQArtemisAddress.v2alpha2.broker.amq.io,ActiveMQArtemisScaledown.v2alpha1.broker.amq.io,Interconnect.v1alpha1.interconnectedcloud.github.io
  name: amq-broker-og
spec:
  targetNamespaces:
    - {TARGET_NAMESPACE}
