apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true


# Installing the Operator in OperatorHub
# https://access.redhat.com/documentation/en-us/red_hat_amq/2020.q4/html/deploying_amq_broker_on_openshift/deploying-broker-on-ocp-using-operator_broker-ocp#proc_br-installing-broker-operator-in-operatorhub_broker-ocp
bases:
- ../../../../base/broker/operator/operatorhub
