apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

commonLabels:
  application: amq-interconnect-edge

# configMapGenerator:
# - name: amq-interconnect
#   files:
#   - conf/qdrouterd.conf



resources:
- svc.yaml
- sa.yaml
- rb.yaml
- dc.yaml
- cm-sasl-config.yaml
- route-console.yaml
- route-amqps.yaml
