kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: amq-mesh-console
spec:
  port:
    targetPort: http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: amq-interconnect-mesh
