apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true


bases:
- ../../../../base/interconnect/mesh

resources:
  - cm.yaml

secretGenerator:
  #https://github.com/jboss-container-images/amq-interconnect-1-openshift-image/pull/20
- name: users-secret-mesh
  envs:
  - users/users.properties
- name: policies-mesh
  files:
    - policies/default.json
    - policies/edge.json
    - policies/inter-router.json
    - policies/public.json
